"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-23 15:04:20.572336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_type', sa.Enum('interval', 'manual', name='poll_trigger_type'), nullable=False),
    sa.Column('repos_polled', sa.Integer(), nullable=False),
    sa.Column('new_issues_found', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_limit_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('is_limited', sa.Boolean(), nullable=False),
    sa.Column('limited_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remaining_calls', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    op.create_table('repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=511), nullable=False),
    sa.Column('repo_type', sa.Enum('sandbox', 'inspected', name='repo_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('baseline_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_session_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repos_full_name'), 'repos', ['full_name'], unique=True)
    op.create_table('email_subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('is_admin_fallback', sa.Boolean(), nullable=False),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unsubscribe_token')
    )
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('html_url', sa.String(length=1024), nullable=True),
    sa.Column('github_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('origin', sa.Enum('baseline', 'poller_detected', 'demo_injected', 'manual_refresh', name='issue_origin'), nullable=False),
    sa.Column('latest_remediation_run_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'issue_number', name='uq_issue_repo_number')
    )
    op.create_table('remediation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('trigger_source', sa.Enum('poller', 'manual_dashboard', 'demo_injected', name='run_trigger_source'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'diagnosed', 'verify_failed', 'awaiting_approval', 'rejected', 'pr_opened', 'failed', name='run_status'), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('diagnosis_summary', sa.Text(), nullable=True),
    sa.Column('root_cause_analysis', sa.Text(), nullable=True),
    sa.Column('affected_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_file', sa.String(length=1024), nullable=True),
    sa.Column('code_fix', sa.Text(), nullable=True),
    sa.Column('git_diff_patch', sa.Text(), nullable=True),
    sa.Column('test_file_name', sa.String(length=255), nullable=True),
    sa.Column('test_code', sa.Text(), nullable=True),
    sa.Column('verification_passed', sa.Boolean(), nullable=True),
    sa.Column('verification_stdout', sa.Text(), nullable=True),
    sa.Column('verification_stderr', sa.Text(), nullable=True),
    sa.Column('fix_attempts', sa.Integer(), nullable=False),
    sa.Column('pr_url', sa.String(length=1024), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # issues.latest_remediation_run_id and remediation_runs.issue_id form a
    # circular FK — remediation_runs must exist before this constraint can
    # be added, so it's applied here rather than inline on the issues table.
    op.create_foreign_key(
        'fk_issue_latest_run', 'issues', 'remediation_runs',
        ['latest_remediation_run_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_issue_latest_run', 'issues', type_='foreignkey')
    op.drop_table('remediation_runs')
    op.drop_table('issues')
    op.drop_table('email_subscribers')
    op.drop_index(op.f('ix_repos_full_name'), table_name='repos')
    op.drop_table('repos')
    op.drop_table('rate_limit_state')
    op.drop_table('poll_runs')
    # ### end Alembic commands ###
